version: '3.8'

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/strongpassword123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local